### ISSUE TITLE
Google Workspace Drive: Upload task showing incorrect size and version

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-googleworkspace#110]
### Expected Behavior

1. On upload of the file, I would expect the file.size output to contain the size of the uploaded file.
2. If the file is being created with a name that does not exist yet in the folder, the version should be 1. On a re-upload of the file with the same name, the version should increase.

### Actual Behaviour

1. On upload of the file, the Outputs show the file size as 1.
2. On upload of the file for the first time, the version is shown as 4 (was expecting 1).

![Screenshot 2024-03-17 at 6 37 24 PM](https://github.com/kestra-io/plugin-googleworkspace/assets/6594483/48ffab56-b9e9-4c02-8bc6-b7ce1c7f9c10)

### Steps To Reproduce

1. Use the upload task in a flow with file input.
2. Upload a file and check the Outputs for the file.size and file.version

### Environment Information

- Kestra Version: 0.15.0
- Plugin version: 0.15.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```yaml
id: drive-upload
namespace: dev
inputs:
  - id: file
    type: FILE
tasks:
  - id: "upload"
    type: "io.kestra.plugin.googleworkspace.drive.Upload"
    from: "{{ inputs.file }}"
    parents:
     - "1rg7AfsdfZ8V2HkBArMB6XXL87M45848j"
    name: "orders.csv"
    contentType: "text/csv"
    mimeType: "application/vnd.google-apps.spreadsheet"
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
```
