### ISSUE TITLE
Google Workspace Drive: Outputs of the Export task has multiple file attributes missing

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-googleworkspace#111]
### Expected Behavior

Expecting all the file attributes in the Outputs.

### Actual Behaviour

Getting only id, name and mimeType of the file that has got uploaded as part of Drive's Upload task.
I was expecting : size, version, trashed and parents as well in the Outputs under the "file" attribute.

![Screenshot 2024-03-17 at 6 42 48 PM](https://github.com/kestra-io/plugin-googleworkspace/assets/6594483/99cf0d30-6d44-4afc-b8ec-4343c2a1e538)

### Steps To Reproduce

1. Use the Export task in the flow that exports a spreadsheet from the drive.
2. Check the Outputs tab for the file attributes.

### Environment Information

- Kestra Version: 0.15.0
- Plugin version: 0.15.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```yaml
id: drive-export
namespace: dev
tasks:
  - id: "export"
    type: "io.kestra.plugin.googleworkspace.drive.Export"
    contentType: "text/csv"
    fileId: "1X-MNXW1hDcFhCJ3vvLLDUyMi-zN2x_quLgI4U1faI9s"
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
```
